# Site
repository: selvamcoding/resume

version: 2

# Personal info
name: Selvam
title: Staff Software Engineer, Walmart
email: selvamgce@yahoo.com

# Social links
github_username:  selvamcoding
linkedin_username: selvam-mariappan

#defaults:
#  -
#    scope:
#      path: ""
#    values:
#      layout: "default"
#
